version: '3'
services:
    postgres:
        image: postgres:latest
        container_name: postgres
        environment:
            POSTGRES_PASSWORD: password
        ports:
            - "5432:5432"
        volumes:
            - pg-data:/var/lib/postgresql/data
        networks:
          - flask_shorten

    flask_shorten:
        restart: always
        command: poetry run gunicorn -w 4 -b 0.0.0.0:5000 run:app --access-logfile - # python run.py
        volumes:
            - ./:/flask_shorten
        build:
            context: .
        ports:
            - "5000:5000"
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_USER: postgres
            POSTGRES_DATABASE: postgres
            POSTGRES_SERVICE: postgres
        depends_on:
            - postgres
        links:
            - postgres
        networks:
            - flask_shorten

volumes:
    pg-data:
        driver: local

networks:
    flask_shorten:
